drop table author if exists;
drop table category if exists;
drop table note if exists;

create table author (
id bigint generated by default as identity,
name varchar(255) not null,
password varchar(255) not null,
primary key (id)
);

create table category (
id bigint generated by default as identity,
name varchar(255) not null,
primary key (id)
);

create table note (
id bigint generated by default as identity,
text varchar(255) not null,
primary key (id),
author_id bigint,
category_id bigint
);

alter table author
    add constraint nc1 unique (name);

alter table category
    add constraint nc2 unique (name);

alter table note
    add constraint nc3 unique (text);

alter table note
    add constraint FKdhrwbbwlcy35n6avchj4nao51
        foreign key (author_id)
            references author;

alter table note
    add constraint FKrvvxymn6mnvx141furq7gp6kf
        foreign key (category_id)
            references category;



